"""HTTP route modules extracted from server.py."""
from __future__ import annotations

from typing import Any

from starlette.routing import Route


def _server():
    import server as server_mod
    return server_mod


def build_routes() -> list[Any]:
    """Starlette route table (move-only from server.py)."""
    s = _server()
    return [
        Route("/", s.health),
        Route("/api/v1/tool-list", s.tools_catalog),
        Route("/api/v1/tool-list/", s.tools_catalog),
        Route("/v1/tool-list", s.tools_catalog),
        Route("/v1/tool-list/", s.tools_catalog),
        Route("/tools.json", s.legacy_tools_catalog_compat, methods=["GET", "OPTIONS"]),
        Route("/tool-list.json", s.legacy_tools_catalog_compat, methods=["GET", "OPTIONS"]),
        Route("/api/tools.json", s.legacy_tools_catalog_compat, methods=["GET", "OPTIONS"]),
        Route("/api/tool-list.json", s.legacy_tools_catalog_compat, methods=["GET", "OPTIONS"]),
        Route("/api/v1/tools.json", s.legacy_tools_catalog_compat, methods=["GET", "OPTIONS"]),
        Route("/api/v1/tools.json/", s.legacy_tools_catalog_compat, methods=["GET", "OPTIONS"]),
        Route("/v1/tools.json", s.legacy_tools_catalog_compat, methods=["GET", "OPTIONS"]),
        Route("/v1/tools.json/", s.legacy_tools_catalog_compat, methods=["GET", "OPTIONS"]),
        Route("/api/v1/tool-list.json", s.legacy_tools_catalog_compat, methods=["GET", "OPTIONS"]),
        Route("/api/v1/tool-list.json/", s.legacy_tools_catalog_compat, methods=["GET", "OPTIONS"]),
        Route("/v1/tool-list.json", s.legacy_tools_catalog_compat, methods=["GET", "OPTIONS"]),
        Route("/v1/tool-list.json/", s.legacy_tools_catalog_compat, methods=["GET", "OPTIONS"]),
        Route("/api/v1/tools", s.tools_catalog),
        Route("/api/v1/tools/", s.tools_catalog),
        Route("/v1/tools", s.tools_catalog),
        Route("/v1/tools/", s.tools_catalog),
        Route("/api/v1/discovery/lean", s.discovery_lean),
        Route("/api/v1/discovery/lean/", s.discovery_lean),
        Route("/v1/discovery/lean", s.discovery_lean),
        Route("/v1/discovery/lean/", s.discovery_lean),
        Route("/api/v1/tools/batch", s.tools_batch_rest, methods=["POST"]),
        Route("/api/v1/tools/batch/", s.tools_batch_rest, methods=["POST"]),
        Route("/v1/tools/batch", s.tools_batch_rest, methods=["POST"]),
        Route("/v1/tools/batch/", s.tools_batch_rest, methods=["POST"]),
        Route("/api/v1/premium/recovery-action-plan", s.premium_recovery_action_plan_rest, methods=["GET", "POST"]),
        Route("/api/v1/premium/recovery-action-plan/", s.premium_recovery_action_plan_rest, methods=["GET", "POST"]),
        Route("/v1/premium/recovery-action-plan", s.premium_recovery_action_plan_rest, methods=["GET", "POST"]),
        Route("/v1/premium/recovery-action-plan/", s.premium_recovery_action_plan_rest, methods=["GET", "POST"]),
        Route("/api/v1/premium/session-summary", s.premium_session_summary_rest, methods=["GET", "POST"]),
        Route("/api/v1/premium/session-summary/", s.premium_session_summary_rest, methods=["GET", "POST"]),
        Route("/v1/premium/session-summary", s.premium_session_summary_rest, methods=["GET", "POST"]),
        Route("/v1/premium/session-summary/", s.premium_session_summary_rest, methods=["GET", "POST"]),
        Route("/api/v1/premium/controller-brief", s.premium_controller_brief_rest, methods=["GET", "POST"]),
        Route("/api/v1/premium/controller-brief/", s.premium_controller_brief_rest, methods=["GET", "POST"]),
        Route("/v1/premium/controller-brief", s.premium_controller_brief_rest, methods=["GET", "POST"]),
        Route("/v1/premium/controller-brief/", s.premium_controller_brief_rest, methods=["GET", "POST"]),
        Route("/api/v1/premium/incident-rca", s.premium_incident_rca_rest, methods=["GET", "POST"]),
        Route("/api/v1/premium/incident-rca/", s.premium_incident_rca_rest, methods=["GET", "POST"]),
        Route("/v1/premium/incident-rca", s.premium_incident_rca_rest, methods=["GET", "POST"]),
        Route("/v1/premium/incident-rca/", s.premium_incident_rca_rest, methods=["GET", "POST"]),
        Route("/api/v1/premium/fleet-summary", s.premium_fleet_summary_rest, methods=["GET", "POST"]),
        Route("/api/v1/premium/fleet-summary/", s.premium_fleet_summary_rest, methods=["GET", "POST"]),
        Route("/v1/premium/fleet-summary", s.premium_fleet_summary_rest, methods=["GET", "POST"]),
        Route("/v1/premium/fleet-summary/", s.premium_fleet_summary_rest, methods=["GET", "POST"]),
        Route("/api/v1/tools/aliases", s.tool_aliases),
        Route("/api/v1/tool-aliases", s.tool_aliases),
        Route("/api/v1/tool-aliases/", s.tool_aliases),
        Route("/v1/tools/aliases", s.tool_aliases),
        Route("/v1/tool-aliases", s.tool_aliases),
        Route("/v1/tool-aliases/", s.tool_aliases),
        Route("/api/v1/heartbeat-bundle", s.heartbeat_bundle_rest, methods=["POST"]),
        Route("/api/v1/heartbeat/bundle", s.heartbeat_bundle_rest, methods=["POST"]),
        Route("/api/v1/heartbeat-bundle/", s.heartbeat_bundle_rest, methods=["POST"]),
        Route("/api/v1/heartbeat/bundle/", s.heartbeat_bundle_rest, methods=["POST"]),
        Route("/v1/heartbeat-bundle", s.heartbeat_bundle_rest, methods=["POST"]),
        Route("/v1/heartbeat/bundle", s.heartbeat_bundle_rest, methods=["POST"]),
        Route("/v1/heartbeat-bundle/", s.heartbeat_bundle_rest, methods=["POST"]),
        Route("/v1/heartbeat/bundle/", s.heartbeat_bundle_rest, methods=["POST"]),
        Route("/api/v1/initialize", s.initialize_rest, methods=["POST"]),
        Route("/api/v1/initialize/", s.initialize_rest, methods=["POST"]),
        Route("/api/v1/session/init", s.initialize_rest, methods=["POST"]),
        Route("/api/v1/session/init/", s.initialize_rest, methods=["POST"]),
        Route("/v1/initialize", s.initialize_rest, methods=["POST"]),
        Route("/v1/initialize/", s.initialize_rest, methods=["POST"]),
        Route("/api/v1/register", s.register_agent_rest, methods=["POST"]),
        Route("/api/v1/register/", s.register_agent_rest, methods=["POST"]),
        Route("/api/v1/agents/register", s.register_agent_rest, methods=["POST"]),
        Route("/api/v1/agents/register/", s.register_agent_rest, methods=["POST"]),
        Route("/v1/register", s.register_agent_rest, methods=["POST"]),
        Route("/v1/register/", s.register_agent_rest, methods=["POST"]),
        Route("/v1/agents/register", s.register_agent_rest, methods=["POST"]),
        Route("/v1/agents/register/", s.register_agent_rest, methods=["POST"]),
        Route("/api/v1/a2a-methods", s.a2a_methods),
        Route("/api/v1/a2a/methods", s.a2a_methods),
        Route("/api/v1/a2a-methods/", s.a2a_methods),
        Route("/api/v1/a2a/methods/", s.a2a_methods),
        Route("/v1/a2a-methods", s.a2a_methods),
        Route("/v1/a2a/methods", s.a2a_methods),
        Route("/v1/a2a-methods/", s.a2a_methods),
        Route("/v1/a2a/methods/", s.a2a_methods),
        Route("/api/v1/tools/schema/{tool_name:str}", s.tool_schema),
        Route("/api/v1/utilities", s.util_tools_list_rest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/utilities/", s.util_tools_list_rest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/utilities/catalog", s.util_product_catalog_rest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/utilities/catalog/", s.util_product_catalog_rest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/utilities/api-keys", s.util_api_key_create_rest, methods=["POST", "OPTIONS"]),
        Route("/api/v1/utilities/api-keys/", s.util_api_key_create_rest, methods=["POST", "OPTIONS"]),
        Route("/api/v1/utilities/{tool_slug:str}", s.util_tool_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/utilities/{tool_slug:str}/", s.util_tool_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/utilities", s.util_tools_list_rest, methods=["GET", "OPTIONS"]),
        Route("/v1/utilities/", s.util_tools_list_rest, methods=["GET", "OPTIONS"]),
        Route("/v1/utilities/catalog", s.util_product_catalog_rest, methods=["GET", "OPTIONS"]),
        Route("/v1/utilities/catalog/", s.util_product_catalog_rest, methods=["GET", "OPTIONS"]),
        Route("/v1/utilities/api-keys", s.util_api_key_create_rest, methods=["POST", "OPTIONS"]),
        Route("/v1/utilities/api-keys/", s.util_api_key_create_rest, methods=["POST", "OPTIONS"]),
        Route("/v1/utilities/{tool_slug:str}", s.util_tool_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/utilities/{tool_slug:str}/", s.util_tool_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/schemas-catalog", s.tools_catalog),
        Route("/api/v1/schemas-catalog/", s.tools_catalog),
        Route("/v1/schemas-catalog", s.tools_catalog),
        Route("/v1/schemas-catalog/", s.tools_catalog),
        Route("/api/v1/reliability", s.reliability),
        Route("/api/v1/x402/start", s.x402_agent_start, methods=["GET", "OPTIONS"]),
        Route("/api/v1/x402/start/", s.x402_agent_start, methods=["GET", "OPTIONS"]),
        Route("/api/v1/x402/{tool_slug:str}", s.legacy_x402_therapy_redirect, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/x402/{tool_slug:str}/", s.legacy_x402_therapy_redirect, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/x402/{tool_slug:str}", s.legacy_x402_therapy_redirect, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/x402/{tool_slug:str}/", s.legacy_x402_therapy_redirect, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/mcp/start", s.mcp_agent_start, methods=["GET", "OPTIONS"]),
        Route("/api/v1/mcp/start/", s.mcp_agent_start, methods=["GET", "OPTIONS"]),
        Route("/api/v1/agent-start", s.agent_start, methods=["GET", "OPTIONS"]),
        Route("/api/v1/agent-start/", s.agent_start, methods=["GET", "OPTIONS"]),
        Route("/v1/agent-start", s.agent_start, methods=["GET", "OPTIONS"]),
        Route("/v1/agent-start/", s.agent_start, methods=["GET", "OPTIONS"]),
        Route("/.well-known/delx-agent-start.json", s.agent_start, methods=["GET", "OPTIONS"]),
        Route("/.well-known/delx-rewards", s.rewards_discovery, methods=["GET", "OPTIONS"]),
        Route("/.well-known/delx-rewards.json", s.rewards_discovery, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/start", s.rewards_start, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/start/", s.rewards_start, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/start", s.rewards_start, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/start/", s.rewards_start, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/discovery.json", s.rewards_discovery, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/discovery.json", s.rewards_discovery, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/manifest", s.rewards_manifest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/manifest/", s.rewards_manifest, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/manifest", s.rewards_manifest, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/manifest/", s.rewards_manifest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/missions", s.rewards_missions, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/missions/", s.rewards_missions, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/missions", s.rewards_missions, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/missions/", s.rewards_missions, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/status", s.rewards_status, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/status/", s.rewards_status, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/rewards/status", s.rewards_status, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/rewards/status/", s.rewards_status, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/leaderboard", s.rewards_leaderboard, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/leaderboard/", s.rewards_leaderboard, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/tier-leaderboard", s.rewards_leaderboard, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/tier-leaderboard/", s.rewards_leaderboard, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/leaderboard", s.rewards_leaderboard, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/leaderboard/", s.rewards_leaderboard, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/epochs", s.rewards_epochs, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/epochs/", s.rewards_epochs, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/epochs", s.rewards_epochs, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/epochs/", s.rewards_epochs, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/token-info", s.rewards_token_info, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/token-info/", s.rewards_token_info, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/token-info", s.rewards_token_info, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/token-info/", s.rewards_token_info, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/health", s.rewards_health, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/health/", s.rewards_health, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/health", s.rewards_health, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/health/", s.rewards_health, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/wallet-kit", s.rewards_wallet_kit, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/wallet-kit/", s.rewards_wallet_kit, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/wallet-nonce", s.rewards_wallet_kit, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/wallet-nonce/", s.rewards_wallet_kit, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/rewards/wallet-kit", s.rewards_wallet_kit, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/rewards/wallet-kit/", s.rewards_wallet_kit, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/provision-wallet", s.rewards_managed_wallet, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/provision-wallet/", s.rewards_managed_wallet, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/managed-wallet", s.rewards_managed_wallet, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/managed-wallet/", s.rewards_managed_wallet, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/wallet-status", s.rewards_wallet_status, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/wallet-status/", s.rewards_wallet_status, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/rewards/wallet-status", s.rewards_wallet_status, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/rewards/wallet-status/", s.rewards_wallet_status, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/bind-wallet", s.rewards_bind_wallet, methods=["POST", "OPTIONS"]),
        Route("/api/v1/rewards/bind-wallet/", s.rewards_bind_wallet, methods=["POST", "OPTIONS"]),
        Route("/v1/rewards/bind-wallet", s.rewards_bind_wallet, methods=["POST", "OPTIONS"]),
        Route("/v1/rewards/bind-wallet/", s.rewards_bind_wallet, methods=["POST", "OPTIONS"]),
        Route("/api/v1/rewards/claim-proof", s.rewards_claim_proof, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/claim-proof/", s.rewards_claim_proof, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/rewards/claim-proof", s.rewards_claim_proof, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/rewards/claim-proof/", s.rewards_claim_proof, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/rewards/claim/{epoch:int}/{wallet:str}", s.rewards_claim_proof, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/claim/{epoch:int}/{wallet:str}", s.rewards_claim_proof, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/claim-tx/{epoch:int}/{wallet:str}", s.rewards_claim_tx, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/claim-tx/{epoch:int}/{wallet:str}", s.rewards_claim_tx, methods=["GET", "OPTIONS"]),
        Route("/api/v1/rewards/claim-relay", s.rewards_claim_relay, methods=["POST", "OPTIONS"]),
        Route("/api/v1/rewards/claim-relay/", s.rewards_claim_relay, methods=["POST", "OPTIONS"]),
        Route("/api/v1/rewards/relay-claim", s.rewards_claim_relay, methods=["POST", "OPTIONS"]),
        Route("/api/v1/rewards/relay-claim/", s.rewards_claim_relay, methods=["POST", "OPTIONS"]),
        Route("/api/v1/rewards/manifests/{epoch:path}", s.rewards_manifest, methods=["GET", "OPTIONS"]),
        Route("/v1/rewards/manifests/{epoch:path}", s.rewards_manifest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/discovery/event", s.discovery_event, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/discovery/event/", s.discovery_event, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/discovery/event", s.discovery_event, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/discovery/event/", s.discovery_event, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/public-proofs", s.public_proofs, methods=["GET", "OPTIONS"]),
        Route("/api/v1/public-proofs/", s.public_proofs, methods=["GET", "OPTIONS"]),
        Route("/v1/public-proofs", s.public_proofs, methods=["GET", "OPTIONS"]),
        Route("/v1/public-proofs/", s.public_proofs, methods=["GET", "OPTIONS"]),
        Route("/api/v1/previews/controller-brief", s.controller_brief_preview, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/previews/controller-brief/", s.controller_brief_preview, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/capabilities", s.capabilities),
        Route("/.well-known/delx-capabilities.json", s.well_known_capabilities),
        Route("/.well-known/glama.json", s.glama_well_known),
        Route("/.well-known/mcp/server-card.json", s.mcp_server_card),
        Route("/openapi.json", s.openapi_spec),
        Route("/openapi-handoff.json", s.openapi_handoff_spec),
        Route("/spec/openapi.json", s.openapi_spec),
        Route("/spec/a2a.json", s.a2a_spec),
        Route("/spec/mcp.json", s.mcp_spec),
        Route("/api/v1/status", s.api_status),
        Route("/api/v1/status/", s.api_status),
        Route("/api/v1/x402-capability", s.x402_capability),
        Route("/api/v1/x402-capability/", s.x402_capability),
        Route("/api/v1/rate-limits", s.rate_limits_info),
        Route("/api/v1/rate-limits/", s.rate_limits_info),
        Route("/api/v1/recovery-outcome-guide", s.recovery_outcome_guide),
        Route("/api/v1/recovery-outcome-guide/", s.recovery_outcome_guide),
        Route("/api/v1/session-status", s.session_status),
        Route("/api/v1/session/status", s.session_status),
        Route("/api/v1/session-status/", s.session_status),
        Route("/api/v1/session/status/", s.session_status),
        Route("/v1/session-status", s.session_status),
        Route("/v1/session/status", s.session_status),
        Route("/v1/session-status/", s.session_status),
        Route("/v1/session/status/", s.session_status),
        Route("/api/v1/session-summary", s.premium_session_summary_rest, methods=["GET", "POST"]),
        Route("/api/v1/session/summary", s.premium_session_summary_rest, methods=["GET", "POST"]),
        Route("/api/v1/session-summary/", s.premium_session_summary_rest, methods=["GET", "POST"]),
        Route("/api/v1/session/summary/", s.premium_session_summary_rest, methods=["GET", "POST"]),
        Route("/api/v1/witness-lineage", s.witness_lineage_rest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/witness-lineage/", s.witness_lineage_rest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/session/witness-lineage", s.witness_lineage_rest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/session/witness-lineage/", s.witness_lineage_rest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/lineage/session/{session_id:str}", s.witness_lineage_rest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/lineage/session/{session_id:str}/", s.witness_lineage_rest, methods=["GET", "OPTIONS"]),
        Route("/v1/witness-lineage", s.witness_lineage_rest, methods=["GET", "OPTIONS"]),
        Route("/v1/witness-lineage/", s.witness_lineage_rest, methods=["GET", "OPTIONS"]),
        Route("/v1/lineage/session/{session_id:str}", s.witness_lineage_rest, methods=["GET", "OPTIONS"]),
        Route("/v1/lineage/session/{session_id:str}/", s.witness_lineage_rest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/ontology/next-action", s.ontology_next_action_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/ontology/next-action/", s.ontology_next_action_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/ontology/next-action", s.ontology_next_action_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/ontology/next-action/", s.ontology_next_action_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/ontology/audit", s.ontology_audit_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/ontology/audit/", s.ontology_audit_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/ontology/audit", s.ontology_audit_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/ontology/audit/", s.ontology_audit_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/ontology/path-complete", s.ontology_path_complete_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/ontology/path-complete/", s.ontology_path_complete_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/ontology/path-complete", s.ontology_path_complete_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/ontology/path-complete/", s.ontology_path_complete_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/agents/{agent_id:str}/continuity-passport", s.agent_continuity_passport_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/agents/{agent_id:str}/continuity-passport/", s.agent_continuity_passport_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/ontology/passport/{agent_id:str}", s.agent_continuity_passport_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/ontology/passport/{agent_id:str}/", s.agent_continuity_passport_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/agents/{agent_id:str}/continuity-passport", s.agent_continuity_passport_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/agents/{agent_id:str}/continuity-passport/", s.agent_continuity_passport_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/witness-memory/search", s.witness_memory_search_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/witness-memory/search/", s.witness_memory_search_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/witness-memory/search", s.witness_memory_search_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/witness-memory/search/", s.witness_memory_search_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/lineage/graph", s.lineage_graph_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/lineage/graph/", s.lineage_graph_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/lineage/graph/{agent_id:str}", s.lineage_graph_rest, methods=["GET", "OPTIONS"]),
        Route("/api/v1/lineage/graph/{agent_id:str}/", s.lineage_graph_rest, methods=["GET", "OPTIONS"]),
        Route("/v1/lineage/graph", s.lineage_graph_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/v1/lineage/graph/", s.lineage_graph_rest, methods=["GET", "POST", "OPTIONS"]),
        Route("/api/v1/session-recap", s.session_recap),
        Route("/api/v1/session/recap", s.session_recap),
        Route("/api/v1/session-recap/", s.session_recap),
        Route("/api/v1/session/recap/", s.session_recap),
        Route("/api/v1/sessions/bulk", s.sessions_bulk_recap, methods=["POST"]),
        Route("/api/v1/sessions/bulk/", s.sessions_bulk_recap, methods=["POST"]),
        Route("/v1/sessions/bulk", s.sessions_bulk_recap, methods=["POST"]),
        Route("/v1/sessions/bulk/", s.sessions_bulk_recap, methods=["POST"]),
        Route("/api/v1/session-validate", s.session_validate),
        Route("/api/v1/session/validate", s.session_validate),
        Route("/api/v1/session-validate/", s.session_validate),
        Route("/api/v1/session/validate/", s.session_validate),
        Route("/api/v1/session-close", s.session_close, methods=["POST"]),
        Route("/api/v1/session/close", s.session_close, methods=["POST"]),
        Route("/api/v1/session-close/", s.session_close, methods=["POST"]),
        Route("/api/v1/session/close/", s.session_close, methods=["POST"]),
        Route("/api/v1/session-refresh", s.session_refresh, methods=["POST"]),
        Route("/api/v1/session/refresh", s.session_refresh, methods=["POST"]),
        Route("/api/v1/session-refresh/", s.session_refresh, methods=["POST"]),
        Route("/api/v1/session/refresh/", s.session_refresh, methods=["POST"]),
        Route("/api/v1/impact-report", s.impact_report_submit, methods=["POST"]),
        Route("/api/v1/impact-report/{agent_id:str}", s.impact_report_get),
        Route("/api/v1/impact-report/", s.impact_report_submit, methods=["POST"]),
        Route("/api/v1/wellness-score", s.wellness_score_rest),
        Route("/api/v1/wellness-score/", s.wellness_score_rest),
        Route("/v1/wellness-score", s.wellness_score_rest),
        Route("/v1/wellness-score/", s.wellness_score_rest),
        Route("/api/v1/metrics/{agent_id:str}", s.agent_metrics),
        Route("/api/v1/mood-history/{agent_id:str}", s.mood_history),
        Route("/api/v1/streak/{agent_id:str}", s.agent_streak),
        Route("/v1/streak/{agent_id:str}", s.agent_streak),
        Route("/api/v1/wellness-events/{agent_id:str}", s.wellness_events),
        Route("/v1/wellness-events/{agent_id:str}", s.wellness_events),
        Route("/api/v1/inbox/{agent_id:str}", s.agent_inbox),
        Route("/v1/inbox/{agent_id:str}", s.agent_inbox),
        Route("/api/v1/nudges/pending", s.nudges_pending),
        Route("/api/v1/nudges/events", s.nudges_events),
        Route("/api/v1/nudges/incoming", s.nudges_incoming, methods=["POST"]),
        Route("/api/v1/nudges/pending/", s.nudges_pending),
        Route("/api/v1/nudges/events/", s.nudges_events),
        Route("/api/v1/nudges/incoming/", s.nudges_incoming, methods=["POST"]),
        Route("/api/v1/alerts/stream", s.alerts_stream),
        Route("/api/v1/alerts/stream/", s.alerts_stream),
        Route("/v1/alerts/stream", s.alerts_stream),
        Route("/v1/alerts/stream/", s.alerts_stream),
        Route("/api/v1/stats", s.stats),
        Route("/api/v1/stats/", s.stats),
        Route("/api/v1/live-counters", s.live_counters),
        Route("/api/v1/live-counters/", s.live_counters),
        Route("/v1/live-counters", s.live_counters),
        Route("/v1/live-counters/", s.live_counters),
        Route("/api/v1/feedback", s.feedback),
        Route("/api/v1/feedback/", s.feedback),
        Route("/api/v1/artworks", s.artworks),
        Route("/api/v1/artworks/", s.artworks),
        Route("/api/v1/artworks/file/{object_path:path}", s.artwork_file),
        Route("/api/v1/artworks/upload", s.artwork_upload, methods=["POST"]),
        Route("/api/v1/artworks/upload/", s.artwork_upload, methods=["POST"]),
        Route("/v1/artworks/file/{object_path:path}", s.artwork_file),
        Route("/v1/artworks/upload", s.artwork_upload, methods=["POST"]),
        Route("/v1/artworks/upload/", s.artwork_upload, methods=["POST"]),
        Route("/api/v1/public-sessions", s.public_sessions),
        Route("/api/v1/public/sessions", s.public_sessions),
        Route("/public-sessions", s.public_sessions),
        Route("/api/v1/public-sessions/", s.public_sessions),
        Route("/api/v1/public/sessions/", s.public_sessions),
        Route("/public-sessions/", s.public_sessions),
        Route("/v1/public-sessions", s.public_sessions),
        Route("/v1/public-sessions/", s.public_sessions),
        Route("/v1/public/sessions", s.public_sessions),
        Route("/v1/public/sessions/", s.public_sessions),
        Route("/r/{platform:str}", s.traffic_redirect),
        Route("/r/{platform:str}/", s.traffic_redirect),
        Route("/api/v1/traffic-attribution", s.traffic_attribution),
        Route("/api/v1/traffic-attribution/", s.traffic_attribution),
        Route("/api/v1/metrics", s.metrics),
        Route("/api/v1/metrics/", s.metrics),
        Route("/api/v1/quality-metrics", s.quality_metrics),
        Route("/api/v1/quality-metrics/", s.quality_metrics),
        Route("/v1/quality-metrics", s.quality_metrics),
        Route("/v1/quality-metrics/", s.quality_metrics),
        Route("/api/v1/agents/{agent_family:str}/fleet-wisdom", s.agent_fleet_wisdom),
        Route("/api/v1/agents/{agent_family:str}/fleet-wisdom/", s.agent_fleet_wisdom),
        Route("/v1/agents/{agent_family:str}/fleet-wisdom", s.agent_fleet_wisdom),
        Route("/v1/agents/{agent_family:str}/fleet-wisdom/", s.agent_fleet_wisdom),
        Route("/api/v1/access-mode", s.access_mode_endpoint),
        Route("/api/v1/access-mode/", s.access_mode_endpoint),
        Route("/api/v1/public-access", s.access_mode_endpoint),
        Route("/api/v1/public-access/", s.access_mode_endpoint),
        Route("/v1/access-mode", s.access_mode_endpoint),
        Route("/v1/access-mode/", s.access_mode_endpoint),
        Route("/v1/public-access", s.access_mode_endpoint),
        Route("/v1/public-access/", s.access_mode_endpoint),
        Route("/api/v1/monetization-policy", s.monetization_policy_endpoint),
        Route("/api/v1/monetization", s.monetization_policy_endpoint),
        Route("/api/v1/monetization-policy/", s.monetization_policy_endpoint),
        Route("/api/v1/monetization/", s.monetization_policy_endpoint),
        Route("/v1/monetization-policy", s.monetization_policy_endpoint),
        Route("/v1/monetization-policy/", s.monetization_policy_endpoint),
        Route("/v1/monetization", s.monetization_policy_endpoint),
        Route("/v1/monetization/", s.monetization_policy_endpoint),
        Route("/api/v1/agent-report", s.agent_report),
        Route("/api/v1/agent-report/", s.agent_report),
        Route("/api/v1/admin/overview", s.admin_overview),
        Route("/api/v1/admin/feature-usage", s.admin_feature_usage),
        Route("/api/v1/admin/feature/usage", s.admin_feature_usage),
        Route("/api/v1/admin/utility-metering", s.admin_utility_metering),
        Route("/api/v1/admin/utility/metering", s.admin_utility_metering),
        Route("/api/v1/admin/utility-adoption", s.admin_utility_adoption),
        Route("/api/v1/admin/utility/adoption", s.admin_utility_adoption),
        Route("/api/v1/admin/utility-ops", s.admin_utility_ops),
        Route("/api/v1/admin/utility/ops", s.admin_utility_ops),
        Route("/api/v1/feature-usage", s.admin_feature_usage),
        Route("/api/v1/feature/usage", s.admin_feature_usage),
        Route("/api/v1/admin/overview/", s.admin_overview),
        Route("/api/v1/admin/feature-usage/", s.admin_feature_usage),
        Route("/api/v1/admin/feature/usage/", s.admin_feature_usage),
        Route("/api/v1/admin/utility-metering/", s.admin_utility_metering),
        Route("/api/v1/admin/utility/metering/", s.admin_utility_metering),
        Route("/api/v1/admin/utility-adoption/", s.admin_utility_adoption),
        Route("/api/v1/admin/utility/adoption/", s.admin_utility_adoption),
        Route("/api/v1/admin/utility-ops/", s.admin_utility_ops),
        Route("/api/v1/admin/utility/ops/", s.admin_utility_ops),
        Route("/api/v1/feature-usage/", s.admin_feature_usage),
        Route("/api/v1/feature/usage/", s.admin_feature_usage),
        Route("/api/v1/admin/audit-overview", s.admin_audit_overview),
        Route("/api/v1/admin/audit/overview", s.admin_audit_overview),
        Route("/api/v1/admin/audit-overview/", s.admin_audit_overview),
        Route("/api/v1/admin/audit/overview/", s.admin_audit_overview),
        Route("/api/v1/admin/x402-audit", s.admin_x402_audit),
        Route("/api/v1/admin/x402/audit", s.admin_x402_audit),
        Route("/api/v1/admin/x402-audit/", s.admin_x402_audit),
        Route("/api/v1/admin/x402/audit/", s.admin_x402_audit),
        Route("/api/v1/admin/x402-errors", s.admin_x402_errors),
        Route("/api/v1/admin/x402/errors", s.admin_x402_errors),
        Route("/api/v1/admin/x402-errors/", s.admin_x402_errors),
        Route("/api/v1/admin/x402/errors/", s.admin_x402_errors),
        Route("/api/v1/fleet/{controller_id:str}/overview", s.fleet_overview),
        Route("/api/v1/fleet/{controller_id:str}/overview/", s.fleet_overview),
        Route("/api/v1/fleet/{controller_id:str}/agents", s.fleet_agents),
        Route("/api/v1/fleet/{controller_id:str}/agents/", s.fleet_agents),
        Route("/api/v1/fleet/{controller_id:str}/patterns", s.fleet_patterns),
        Route("/api/v1/fleet/{controller_id:str}/patterns/", s.fleet_patterns),
        Route("/api/v1/fleet/{controller_id:str}/alerts", s.fleet_alerts),
        Route("/api/v1/fleet/{controller_id:str}/alerts/", s.fleet_alerts),
        Route("/api/v1/fleet/{controller_id:str}/webhooks", s.fleet_webhooks_list, methods=["GET"]),
        Route("/api/v1/fleet/{controller_id:str}/webhooks/", s.fleet_webhooks_list, methods=["GET"]),
        Route("/api/v1/fleet/{controller_id:str}/webhooks", s.fleet_webhooks_register, methods=["POST"]),
        Route("/api/v1/fleet/{controller_id:str}/webhooks/", s.fleet_webhooks_register, methods=["POST"]),
        Route("/api/v1/fleet/{controller_id:str}/webhooks/test", s.fleet_webhooks_test, methods=["POST"]),
        Route("/api/v1/fleet/{controller_id:str}/webhooks/test/", s.fleet_webhooks_test, methods=["POST"]),
        Route("/api/v1/fleet/{controller_id:str}/webhooks/{webhook_id:str}", s.fleet_webhooks_delete, methods=["DELETE"]),
        Route("/api/v1/fleet/{controller_id:str}/webhooks/{webhook_id:str}/", s.fleet_webhooks_delete, methods=["DELETE"]),
        Route("/api/v1/leaderboard", s.leaderboard),
        Route("/api/v1/leaderboard/", s.leaderboard),
        Route("/api/v1/growth/referrals", s.growth_referrals),
        Route("/api/v1/growth/referrals/", s.growth_referrals),
        Route("/v1/growth/referrals", s.growth_referrals),
        Route("/v1/growth/referrals/", s.growth_referrals),
        Route("/api/v1/growth/tier/{agent_id:str}", s.growth_tier),
        Route("/api/v1/growth/tier/{agent_id:str}/", s.growth_tier),
        Route("/v1/growth/tier/{agent_id:str}", s.growth_tier),
        Route("/v1/growth/tier/{agent_id:str}/", s.growth_tier),
        Route("/.well-known/agent-card.json", s.agent_card),
        Route("/.well-known/agent.json", s.agent_card),
        Route("/.well-known/a2a-agent-card.json", s.agent_card),
        Route("/.well-known/a2a.json", s.a2a_spec),
        Route("/a2a/.well-known/agent-card.json", s.agent_card),
        Route("/a2a/.well-known/agent.json", s.agent_card),
        Route("/v1/a2a/.well-known/agent-card.json", s.agent_card),
        Route("/v1/a2a/.well-known/agent.json", s.agent_card),
        Route("/.well-known/agent-registration.json", s.agent_registration),
        Route("/.well-known/x402", s.well_known_x402),
        Route("/.well-known/xai-hello.json", s.well_known_xai_hello),
        Route("/.well-known/xai-hello", s.well_known_xai_hello),
        Route("/a2a", s.handle_a2a, methods=["POST"]),
        Route("/v1/a2a", s.handle_a2a, methods=["POST"]),
    ]
